name: ci
on:
    push:
        branches:
            - master
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                  virtualenvs-create: true
                  virtualenvs-in-project: true
                  installer-parallel: true
            - name: Install dependencies
              run: poetry install --no-interaction --no-root
            - name: Setup doc deploy
              run: |
                  git config --global user.name Docs deploy
                  git config --global user.email docs@dummy.bot.com
            - name: Launch test
              run: make test
